name: "Insignia Rocks"
description: "A demo hello world for Insignia Training"
author: "@igorcosta"
branding:
  icon: "award"
  color: "green"

inputs:
  sayMyName:
    description: "Say your name"
    default: "GitHub"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{inputs.sayMyName}}
  
